### ISSUE TITLE
Icon is missing in Termiando

### ISSUE THREAD

**Issue by getmoremx** [BlickLabs/Bricksa#14]
We are also missing an icon in the status Terminado. Please take a look at all the categories and status, an icon should belong to all of them.

**Comment by inesiwadare** [comment]
Where can I see all the Categories? @amorenoh90

**Comment by getmoremx** [comment]
These are the categories @inesiwadare : 
<img width="228" alt="captura de pantalla 2016-10-11 a las 4 54 01 p m" src="https://cloud.githubusercontent.com/assets/8682071/19288280/64541f50-8fd3-11e6-89aa-538b51763952.png">

**Comment by inesiwadare** [comment]
I'm sending icon "Terminado" to @AlanSanchezP now.
