### ISSUE TITLE
0 as default should not appear 

### ISSUE THREAD

**Issue by getmoremx** [BlickLabs/Bricksa#15]
There are some fields that have a zero by default. If it stays, that field shouldnt appear on the clients view.

This view is at the project Casa Residencial del Lago:
<img width="439" alt="captura de pantalla 2016-10-11 a las 2 31 33 p m" src="https://cloud.githubusercontent.com/assets/8682071/19283369/890dbf90-8fbf-11e6-9f1c-8e872131fc4c.png">

**Comment by MauricioDinki** [comment]
This field is not validated to this, this case does not exist, theres no project with 0m2
