### ISSUE TITLE
Create Homepage

### ISSUE THREAD

**Issue by MauricioDinki** [BlickLabs/Bricksa#3]
- [x] Add information for banners in the homepage
- [x] Style the homepage

**Comment by AlanSanchezP** [comment]
@MauricioDinki
Project category name must be in spanish. It is also necessary to include the project id so that the 'conoce más' button could work.

**Comment by MauricioDinki** [comment]
@AlanSanchezP You need to run the command python manage.py compilemessages -l es to compile the traductions

**Comment by AlanSanchezP** [comment]
@MauricioDinki 
Banner description length is too short to put the descriptions that are in the PDF's.
